package com.tranzo.custody.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * All available app themes.
 * Each theme defines a Material 3 color scheme + status bar style.
 */
enum class AppThemeId(val displayName: String) {
    CLASSIC("Classic"),
    MIDNIGHT("Midnight"),
    OCEAN("Ocean"),
    SUNSET("Sunset"),
    FOREST("Forest"),
    LAVENDER("Lavender"),
    ROSE_GOLD("Rose Gold");
}

data class TranzoAppTheme(
    val id: AppThemeId,
    val displayName: String,
    val isDark: Boolean,
    val primary: Color,
    val onPrimary: Color,
    val background: Color,
    val surface: Color,
    val surfaceSecondary: Color,
    val cardBackground: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val accent: Color,
    val accentLight: Color,
    val positive: Color,
    val negative: Color,
    val border: Color,
    val divider: Color,
    val cardDarkStart: Color,
    val cardDarkEnd: Color,
)

val AppThemes: Map<AppThemeId, TranzoAppTheme> = mapOf(
    // ── 1. Classic (existing light black/white) ──
    AppThemeId.CLASSIC to TranzoAppTheme(
        id = AppThemeId.CLASSIC,
        displayName = "Classic",
        isDark = false,
        primary = Color(0xFF000000),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFFFFF),
        surface = Color(0xFFFFFFFF),
        surfaceSecondary = Color(0xFFF7F7F8),
        cardBackground = Color(0xFFFAFAFA),
        textPrimary = Color(0xFF000000),
        textSecondary = Color(0xFF727272),
        textMuted = Color(0xFF999999),
        accent = Color(0xFF000000),
        accentLight = Color(0xFF1A1A1A),
        positive = Color(0xFF10B981),
        negative = Color(0xFFEF4444),
        border = Color(0x0F000000),
        divider = Color(0x0A000000),
        cardDarkStart = Color(0xFF1A1A1A),
        cardDarkEnd = Color(0xFF2D2D2D),
    ),

    // ── 2. Midnight (Neumorphic Slate) ──
    AppThemeId.MIDNIGHT to TranzoAppTheme(
        id = AppThemeId.MIDNIGHT,
        displayName = "Midnight",
        isDark = true,
        primary = Color(0xFFFFFFFF),
        onPrimary = Color(0xFF1C1E21),
        background = Color(0xFF1C1E21), // Soft Slate
        surface = Color(0xFF1C1E21),    // Same as background for Neumorphism
        surfaceSecondary = Color(0xFF22252A),
        cardBackground = Color(0xFF1C1E21),
        textPrimary = Color(0xFFE2E8F0),
        textSecondary = Color(0xFF94A3B8),
        textMuted = Color(0xFF64748B),
        accent = Color(0xFF38BDF8),
        accentLight = Color(0xFF7DD3FC),
        positive = Color(0xFF34D399),
        negative = Color(0xFFF87171),
        border = Color(0x33FFFFFF),
        divider = Color(0x1AFFFFFF),
        cardDarkStart = Color(0xFF24272B),
        cardDarkEnd = Color(0xFF2C3036),
    ),

    // ── 3. Ocean (deep blue) ──
    AppThemeId.OCEAN to TranzoAppTheme(
        id = AppThemeId.OCEAN,
        displayName = "Ocean",
        isDark = true,
        primary = Color(0xFF60A5FA),
        onPrimary = Color(0xFF0A1929),
        background = Color(0xFF0A1929),
        surface = Color(0xFF112240),
        surfaceSecondary = Color(0xFF1A3358),
        cardBackground = Color(0xFF152A4A),
        textPrimary = Color(0xFFE2E8F0),
        textSecondary = Color(0xFF94A3B8),
        textMuted = Color(0xFF64748B),
        accent = Color(0xFF60A5FA),
        accentLight = Color(0xFF93C5FD),
        positive = Color(0xFF34D399),
        negative = Color(0xFFF87171),
        border = Color(0x1A60A5FA),
        divider = Color(0x0D60A5FA),
        cardDarkStart = Color(0xFF1E3A5F),
        cardDarkEnd = Color(0xFF2B4F7A),
    ),

    // ── 4. Sunset (warm orange/amber) ──
    AppThemeId.SUNSET to TranzoAppTheme(
        id = AppThemeId.SUNSET,
        displayName = "Sunset",
        isDark = false,
        primary = Color(0xFFEA580C),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFFBF5),
        surface = Color(0xFFFFFFFF),
        surfaceSecondary = Color(0xFFFFF7ED),
        cardBackground = Color(0xFFFFF9F0),
        textPrimary = Color(0xFF1C1917),
        textSecondary = Color(0xFF78716C),
        textMuted = Color(0xFFA8A29E),
        accent = Color(0xFFEA580C),
        accentLight = Color(0xFFFB923C),
        positive = Color(0xFF16A34A),
        negative = Color(0xFFDC2626),
        border = Color(0x0FEA580C),
        divider = Color(0x0AEA580C),
        cardDarkStart = Color(0xFF9A3412),
        cardDarkEnd = Color(0xFFC2410C),
    ),

    // ── 5. Forest (rich green) ──
    AppThemeId.FOREST to TranzoAppTheme(
        id = AppThemeId.FOREST,
        displayName = "Forest",
        isDark = true,
        primary = Color(0xFF4ADE80),
        onPrimary = Color(0xFF052E16),
        background = Color(0xFF052E16),
        surface = Color(0xFF0A3D22),
        surfaceSecondary = Color(0xFF14532D),
        cardBackground = Color(0xFF0F4429),
        textPrimary = Color(0xFFE2F5E9),
        textSecondary = Color(0xFF86EFAC),
        textMuted = Color(0xFF4ADE80),
        accent = Color(0xFF4ADE80),
        accentLight = Color(0xFF86EFAC),
        positive = Color(0xFF34D399),
        negative = Color(0xFFFB7185),
        border = Color(0x1A4ADE80),
        divider = Color(0x0D4ADE80),
        cardDarkStart = Color(0xFF166534),
        cardDarkEnd = Color(0xFF15803D),
    ),

    // ── 6. Lavender (soft purple) ──
    AppThemeId.LAVENDER to TranzoAppTheme(
        id = AppThemeId.LAVENDER,
        displayName = "Lavender",
        isDark = false,
        primary = Color(0xFF7C3AED),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFAF5FF),
        surface = Color(0xFFFFFFFF),
        surfaceSecondary = Color(0xFFF3E8FF),
        cardBackground = Color(0xFFF5F0FF),
        textPrimary = Color(0xFF1E1B2E),
        textSecondary = Color(0xFF6B7280),
        textMuted = Color(0xFF9CA3AF),
        accent = Color(0xFF7C3AED),
        accentLight = Color(0xFFA78BFA),
        positive = Color(0xFF10B981),
        negative = Color(0xFFEF4444),
        border = Color(0x0F7C3AED),
        divider = Color(0x0A7C3AED),
        cardDarkStart = Color(0xFF5B21B6),
        cardDarkEnd = Color(0xFF7C3AED),
    ),

    // ── 7. Rose Gold (elegant pink) ──
    AppThemeId.ROSE_GOLD to TranzoAppTheme(
        id = AppThemeId.ROSE_GOLD,
        displayName = "Rose Gold",
        isDark = false,
        primary = Color(0xFFBE185D),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFF1F2),
        surface = Color(0xFFFFFFFF),
        surfaceSecondary = Color(0xFFFFE4E6),
        cardBackground = Color(0xFFFFF5F6),
        textPrimary = Color(0xFF1C1917),
        textSecondary = Color(0xFF78716C),
        textMuted = Color(0xFFA8A29E),
        accent = Color(0xFFBE185D),
        accentLight = Color(0xFFE11D72),
        positive = Color(0xFF10B981),
        negative = Color(0xFFEF4444),
        border = Color(0x0FBE185D),
        divider = Color(0x0ABE185D),
        cardDarkStart = Color(0xFF9F1239),
        cardDarkEnd = Color(0xFFBE185D),
    ),
)
