package com.tranzo.custody.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * All available app themes.
 * Each theme defines a Material 3 color scheme + status bar style.
 */
enum class AppThemeId(val displayName: String) {
    CLASSIC("Classic"),
    MIDNIGHT("Midnight"),
    OCEAN("Ocean"),
    SUNSET("Sunset"),
    FOREST("Forest"),
    LAVENDER("Lavender"),
    ROSE_GOLD("Rose Gold");
}

data class TranzoAppTheme(
    val id: AppThemeId,
    val displayName: String,
    val isDark: Boolean,
    val primary: Color,
    val onPrimary: Color,
    val background: Color,
    val surface: Color,
    val surfaceSecondary: Color,
    val cardBackground: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val accent: Color,
    val accentLight: Color,
    val positive: Color,
    val negative: Color,
    val border: Color,
    val divider: Color,
    val cardDarkStart: Color,
    val cardDarkEnd: Color,
)

val AppThemes: Map<AppThemeId, TranzoAppTheme> = mapOf(
    // ── 1. Classic (clean minimal light) ──
    AppThemeId.CLASSIC to TranzoAppTheme(
        id = AppThemeId.CLASSIC,
        displayName = "Classic",
        isDark = false,
        primary = Color(0xFF1A1A2E),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFF8F9FC),
        surface = Color(0xFFFFFFFF),
        surfaceSecondary = Color(0xFFF0F1F5),
        cardBackground = Color(0xFFFFFFFF),
        textPrimary = Color(0xFF1A1A2E),
        textSecondary = Color(0xFF6B7280),
        textMuted = Color(0xFF9CA3AF),
        accent = Color(0xFF635BFF),
        accentLight = Color(0xFF8B5CF6),
        positive = Color(0xFF10B981),
        negative = Color(0xFFEF4444),
        border = Color(0x14000000),
        divider = Color(0x0A000000),
        cardDarkStart = Color(0xFF1A1A2E),
        cardDarkEnd = Color(0xFF2D2D4E),
    ),

    // ── 2. Midnight — Premium dark crypto (DEFAULT) ──
    AppThemeId.MIDNIGHT to TranzoAppTheme(
        id = AppThemeId.MIDNIGHT,
        displayName = "Midnight",
        isDark = true,
        primary = Color(0xFF635BFF),        // Vibrant indigo
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFF0B0D17),     // Deep navy-black
        surface = Color(0xFF141829),        // Slightly lighter
        surfaceSecondary = Color(0xFF1C2039),
        cardBackground = Color(0xFF1E2235),
        textPrimary = Color(0xFFEEEFF5),
        textSecondary = Color(0xFF8E93A7),
        textMuted = Color(0xFF5A5F73),
        accent = Color(0xFF635BFF),
        accentLight = Color(0xFF8B5CF6),
        positive = Color(0xFF34D399),
        negative = Color(0xFFEF4444),
        border = Color(0xFF2A2E45),
        divider = Color(0xFF1F2337),
        cardDarkStart = Color(0xFF1A1D2E),
        cardDarkEnd = Color(0xFF252842),
    ),

    // ── 3. Ocean (deep blue) ──
    AppThemeId.OCEAN to TranzoAppTheme(
        id = AppThemeId.OCEAN,
        displayName = "Ocean",
        isDark = true,
        primary = Color(0xFF60A5FA),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFF0A1628),
        surface = Color(0xFF0F1D36),
        surfaceSecondary = Color(0xFF162A4A),
        cardBackground = Color(0xFF1A2F50),
        textPrimary = Color(0xFFE8EDF5),
        textSecondary = Color(0xFF7B9CC4),
        textMuted = Color(0xFF4A6A8F),
        accent = Color(0xFF60A5FA),
        accentLight = Color(0xFF93C5FD),
        positive = Color(0xFF34D399),
        negative = Color(0xFFF87171),
        border = Color(0xFF1E3A5F),
        divider = Color(0xFF152D4D),
        cardDarkStart = Color(0xFF1E3A5F),
        cardDarkEnd = Color(0xFF2B4F7A),
    ),

    // ── 4. Sunset (warm dark amber) ──
    AppThemeId.SUNSET to TranzoAppTheme(
        id = AppThemeId.SUNSET,
        displayName = "Sunset",
        isDark = true,
        primary = Color(0xFFFB923C),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFF1A1008),
        surface = Color(0xFF241A0E),
        surfaceSecondary = Color(0xFF2E2214),
        cardBackground = Color(0xFF322618),
        textPrimary = Color(0xFFF5EDE3),
        textSecondary = Color(0xFFA89070),
        textMuted = Color(0xFF7A6548),
        accent = Color(0xFFFB923C),
        accentLight = Color(0xFFFBBF24),
        positive = Color(0xFF34D399),
        negative = Color(0xFFEF4444),
        border = Color(0xFF3D3020),
        divider = Color(0xFF2E2214),
        cardDarkStart = Color(0xFF9A3412),
        cardDarkEnd = Color(0xFFC2410C),
    ),

    // ── 5. Forest (rich green) ──
    AppThemeId.FOREST to TranzoAppTheme(
        id = AppThemeId.FOREST,
        displayName = "Forest",
        isDark = true,
        primary = Color(0xFF4ADE80),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFF061A0E),
        surface = Color(0xFF0C2418),
        surfaceSecondary = Color(0xFF132E20),
        cardBackground = Color(0xFF173424),
        textPrimary = Color(0xFFE2F5E9),
        textSecondary = Color(0xFF6DAF83),
        textMuted = Color(0xFF4A8060),
        accent = Color(0xFF4ADE80),
        accentLight = Color(0xFF86EFAC),
        positive = Color(0xFF34D399),
        negative = Color(0xFFFB7185),
        border = Color(0xFF1E4430),
        divider = Color(0xFF153826),
        cardDarkStart = Color(0xFF166534),
        cardDarkEnd = Color(0xFF15803D),
    ),

    // ── 6. Lavender (deep purple) ──
    AppThemeId.LAVENDER to TranzoAppTheme(
        id = AppThemeId.LAVENDER,
        displayName = "Lavender",
        isDark = true,
        primary = Color(0xFFA78BFA),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFF110E1F),
        surface = Color(0xFF1A1530),
        surfaceSecondary = Color(0xFF221C3E),
        cardBackground = Color(0xFF261F44),
        textPrimary = Color(0xFFEDE8F5),
        textSecondary = Color(0xFF9487B5),
        textMuted = Color(0xFF6A5F88),
        accent = Color(0xFFA78BFA),
        accentLight = Color(0xFFC4B5FD),
        positive = Color(0xFF34D399),
        negative = Color(0xFFEF4444),
        border = Color(0xFF322A52),
        divider = Color(0xFF261F44),
        cardDarkStart = Color(0xFF5B21B6),
        cardDarkEnd = Color(0xFF7C3AED),
    ),

    // ── 7. Rose Gold (elegant dark pink) ──
    AppThemeId.ROSE_GOLD to TranzoAppTheme(
        id = AppThemeId.ROSE_GOLD,
        displayName = "Rose Gold",
        isDark = true,
        primary = Color(0xFFF472B6),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFF1A0E14),
        surface = Color(0xFF24151E),
        surfaceSecondary = Color(0xFF2E1C26),
        cardBackground = Color(0xFF32202B),
        textPrimary = Color(0xFFF5E8EE),
        textSecondary = Color(0xFFA87890),
        textMuted = Color(0xFF7A5568),
        accent = Color(0xFFF472B6),
        accentLight = Color(0xFFFB7DB8),
        positive = Color(0xFF34D399),
        negative = Color(0xFFEF4444),
        border = Color(0xFF3D2832),
        divider = Color(0xFF2E1C26),
        cardDarkStart = Color(0xFF9F1239),
        cardDarkEnd = Color(0xFFBE185D),
    ),
)
